### PR TITLE
Make owner delete great again

### PR DESCRIPTION
**Pull request by szero**
- applied dry.js where it was possible
- replaced broken admin "owner" event with user "info_owner" event
- minor style alignment fixes

### CODE REVIEW

**Comment by szero** [comment]
@RealDolos will you merge if I'll replace checkboxes with vola's file highlights?

**Comment by ghost** [comment]
little issue found: 
if the connection is interrupted with the tab still open, the script creates another instance of the trash bin button on reconnect:
screenshot 2019-01-19 at 17 28 15

**Comment by ghost** [comment]
Fixed. You rock.

**Comment by ghost** [comment]
using 0.50
the bin button shows on every room, even the one where the user doesn't have ownership/janitor-ness

**Comment by ghost** [comment]
but now the checkboxes are gone :')

**Review by RealDolos — CHANGES_REQUESTED** [review]
As already pointed out, the logic for per-user select is broken, looking at `e.target` indiscriminately, therefore breaking when the wrong element within a file element is clicked.

**Pull request closed without merging**
